-- Banco de dados
CREATE DATABASE IF NOT EXISTS PRESS_START_TO_HELP;
USE PRESS_START_TO_HELP;

-- Tabela de questionários
CREATE TABLE QUESTIONARIOS (
    ID_QUESTIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(150) NOT NULL,
    DESCRICAO TEXT,
    ATIVO BOOLEAN DEFAULT TRUE,
    CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de perguntas
CREATE TABLE QUESTOES (
    ID_QUESTAO INT AUTO_INCREMENT PRIMARY KEY,
    ID_QUESTIONARIO INT NOT NULL,
    QUESTAO TEXT NOT NULL,
    TIPO VARCHAR(20) NOT NULL, -- 'única', 'múltipla', 'texto', 'número', 'booleano'
    OBRIGATORIA BOOLEAN DEFAULT TRUE,
    ORDEM INT DEFAULT 0,
    FOREIGN KEY (ID_QUESTIONARIO) REFERENCES QUESTIONARIOS(ID_QUESTIONARIO) ON DELETE CASCADE
);

-- Tabela de respostas possíveis
CREATE TABLE RESPOSTAS (
    ID_RESPOSTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_QUESTAO INT NOT NULL,
    RESPOSTA TEXT NOT NULL,
    VALOR DECIMAL DEFAULT 0, -- pontuação para mapeamento
    PROX_QUESTAO INT DEFAULT NULL, -- lógica de fluxo do questionário
    ORDEM INT DEFAULT 0,
    FOREIGN KEY (ID_QUESTAO) REFERENCES QUESTOES(ID_QUESTAO) ON DELETE CASCADE
);

-- Tabela de respostas dos usuários (anônimas)
CREATE TABLE RESULTADOS (
    ID_RESULTADO INT AUTO_INCREMENT PRIMARY KEY,
    ID_QUESTIONARIO INT NOT NULL,
    ID_SESSAO VARCHAR(50), -- identifica a sessão do usuário
    PERMISSAO_LOC BOOLEAN DEFAULT FALSE,
    LATITUDE DECIMAL(10,7),
    LONGITUDE DECIMAL(10,7),
    CIDADE VARCHAR(100),
    ESTADO VARCHAR(50),
    CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_QUESTIONARIO) REFERENCES questionarios(ID_QUESTIONARIO) ON DELETE CASCADE
);

-- Tabela de postos/ unidades de saúde
CREATE TABLE IF NOT EXISTS POSTOS_SAUDE (
  ID_POSTO INT AUTO_INCREMENT PRIMARY KEY,
  CODIGO_CNES BIGINT UNIQUE,              -- Identificador nacional do posto
  NOME VARCHAR(200) NOT NULL,             -- Nome fantasia ou razão social
  ENDERECO VARCHAR(255),                  -- Rua + número + bairro
  CEP VARCHAR(10),                        -- CEP
  TELEFONE VARCHAR(50),                   -- Telefone de contato
  TIPO VARCHAR(50),                       -- 'UBS','UPA','Hospital','Bombeiro'...
  LATITUDE DECIMAL(10,7),                 -- Coordenada latitude
  LONGITUDE DECIMAL(10,7),                -- Coordenada longitude
  HORA_FUNC VARCHAR(255),                 -- Descrição do horário de atendimento
  CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela para armazenar respostas anônimas com consentimento de localização
CREATE TABLE IF NOT EXISTS PERMISSOES (
  ID_PERMISSAO INT AUTO_INCREMENT PRIMARY KEY,
  ID_QUESTIONARIO INT DEFAULT NULL,
  ID_SESSAO VARCHAR(100),
  PERMISSAO_LOC BOOLEAN DEFAULT FALSE,
  LATITUDE DECIMAL(9,6),
  LONGITUDE DECIMAL(9,6),
  CIDADE VARCHAR(100),
  ESTADO VARCHAR(50),
  CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);